import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "../styles/main.scss";
import TopHeader from "@/components/common/Header/TopHeader";
import Footer from "@/components/common/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import AcceptCookies from "@/components/modal/AcceptCookies";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "The Bank Cafe",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <ToastContainer />
        <AcceptCookies/>
        <TopHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
