"use client";
import React from "react";
import { Container } from "react-bootstrap";

const PrivacyPolicyPage = () => {
  return (
    <Container className="bg-white">
      <div className="privacy_policy_section">
        <h1>Privacy Policy</h1>
        <h2>INTRODUCTION</h2>
        <p>All references to “Company,” “we,” “us,” and “our” shall mean Castlebank Hotels & Restaurants LTD.’s privacy policy (“Privacy Policy”) tells you about the information Company, its subsidiaries, and affiliates collect. In addition, it explains how we use that information and how you can opt out of certain uses of information we may collect. If the practices described in this Privacy Policy are not acceptable to you, you should not provide the Company with information about yourself. </p>
        <p>We are committed to providing you with the best products and services possible and we endeavor to protect your personal privacy. We provide this Privacy Statement to help you to understand what we may do with any personal information that we obtain from you. By providing your personal information to us, you signify your acceptance of our Privacy Statement and agree that we may collect, use and disclose your personal information as described in this Privacy Statement. If you do not agree to this statement, please do not provide your personal details to us. This Privacy Statement is incorporated into, and part of, the Terms and Conditions, which govern your use of the site in general.</p>
        <p>We may need to update this Privacy Statement from time to time. We encourage you to check the date of our Privacy Policy whenever you visit our Website for any updates or changes.</p>
        <h2>WHAT IS PERSONAL INFORMATION?</h2>
        <p>“Personal Information” refers to information that relates to an identified, or identifiable, person. This includes, for example, your first and last name, home address or email address. In addition to Personal Information, we also collect information that does not identify you, including age range and gender, or de-identified or aggregated information. The Personal Information that we collect depends on what services you use or information that you request. We may also collect your information as we have a legitimate in many situations interest in maintaining your information after your transaction is complete so that we can quickly and easily respond to any questions about your order. As a result, our collection and processing of your information is based in different contexts upon your consent, our need to perform a contract, our obligations under law, our legitimate interest in conducting our business, protection of a natural person’s vital interests and/or upon your consent.</p>
        <h2>COLLECTING PERSONAL INFORMATION</h2>
        <p>It is your choice to provide us with personal information. We will only collect personal information that you choose to provide. In certain instances, we may provide you with the option to select whether you would like to receive information from us or from trusted third parties (for example, by choosing to opt-in or opt-out of receiving special promotional offers). In some circumstances, you will not have the option to opt-out, such as when we are satisfying the obligations of a contract with you, administering a transaction requested by you, or as required by law. </p>
        <p>We collect information about you (such as your name, address, phone number and email address) when you register with us, sign up for emails, e-mail us, or contact us via social media sites using the links on our website, forward an item to a friend; purchase an item; fill out a survey or other form with your personal information included; request us to provide you with information; enter a competition; post information to public areas of the site; or take advantage of a promotion.  </p>
        <p>By providing any personal information to us, you fully understand and clearly consent to the transfer of such personal information to, and the collection and processing of such information in, other countries or territories. Any such transfer and processing by us will be in accordance with this Privacy Statement.</p>
        <h2>RECORDS OF WEBSITE USE</h2>
        <p>Our website server automatically records information that your browser sends whenever you visit a page on our website, such as your IP address; details of the web browser and operating system that you are using; the date and time of your request; the specific page requested and how you arrived at that page (eg, the search term used to find the page or link clicked to access it). This is statistical data about our users’ browsing actions and patterns and does not identify any individual.</p>
        <h2>USE OF YOUR PERSONAL INFORMATION</h2>
        <p>In addition to the purposes and uses described elsewhere in this Privacy Policy, we use information in the following ways:</p>
        <ul className="policy_ul">
          <li>To record your reservation or booking and/or otherwise register you as a customer.</li>
          <li>To process and deliver orders you make with us including: (a)Manage payments, fees, and charges(b) Collect and recover money owed to us.</li>
          <li>To manage our relationship with you which will include: (a)Notifying you about information relevant to your reservation or booking with us (b)Notifying you about changes to our terms or  privacy policy (c)Asking you to leave a review or take a survey.</li>
          <li>To identify you when you visit our Website or our locations.</li>
          <li>To provide products and services or to process returns.</li>
          <li>To improve our services and product offerings.</li>
          <li>To streamline the checkout process.</li>
          <li>To conduct analytics.</li>
          <li>To respond to inquiries related to support, employment opportunities, or other requests.</li>
          <li>To send marketing and promotional materials, including information relating to our products, services, sales, or promotions.</li>
          <li>For internal administrative purposes, as well as to manage our relationships.</li>
        </ul>
        <h2>USE OF COOKIES ON OUR WEBSITES</h2>
        <p>In common with many websites, we use “cookies” to help us gather and store information about visitors to our websites. A cookie is a small data file that our server sends to your browser when you visit the site. These cookies are necessary for the Sites to function and cannot be switched off in our systems. They are usually only set in response to actions made by you which amount to a request for services, such as setting your privacy preferences, logging in or filling in forms. The use of cookies helps us to assist your use of certain aspects of the site. We may store information about your use of our site and preferences by using cookies which are stored on your computer’s hard drive. Please note that our advertisers may also use cookies. You may refuse to accept cookies or receive notification when you receive cookies by adjusting your privacy settings in your browser. However, if you refuse cookies in a few cases you may be unable to access certain parts of our site or to use all of its functionality. You can obtain information about how to manage cookies at <a href="https://www.aboutcookies.org/" target="_blank">www.aboutcookies.org.</a></p>
        <p>By continuing to browse on our Site(s) you consent to us deploying cookies as described in this policy. </p>
        <h2>DISCLOSURE OF PERSONAL INFORMATION</h2>
        <p>We value your personal information and only share such information with third parties that provide adequate protection for such information. From time to time we may disclose personal information to: </p>
        <p>(a) to members of our group of companies (who will adhere to our Privacy Policy when using your information);</p>
        <p>(b) third parties to whom you have provided your consent;</p>
        <p>(c) our service providers and subcontractors, including our affiliates, retained to perform functions on our behalf or to provide services to us, such as warehousing and delivery; marketing and advertising; credit card and data processing; age verification; software development; website hosting and management; information technology and office services; legal, accounting, audit and other professional service providers; and other services related to our business; and further, provided such service providers and subcontractors do not collect, use or disclose the personal information for any purpose other than to perform such functions on our behalf or to provide services to us or as otherwise required by law;</p>
        <p>(d) third parties who, in our reasonable judgment, are providing or seeking the information as the authorized or appointed legal agent of the subject individual; or</p>
        <p>(e) carefully selected third parties, including our affiliates, to send you third party marketing and promotional information that may be of interest to you. In such circumstances your personal information may be disclosed to these organizations that will be bound by confidentiality obligations and restrictions on use of personal information. We will obtain your express permission before we allow a third party that is not an affiliate to send you any such marketing and promotional information;</p>
        <p>(f) a person or entity, including our affiliates, in the event of a sale, merger, consolidation, change in control, transfer of substantial assets, financing, reorganization or liquidation, whereby we transfer, sell, or assign to such third party information concerning your relationship with us, including without limitation, personally identifiable information that you provide and other information concerning your relationship with us; and</p>
        <p>(g) law enforcement, governmental or regulatory agencies, or other third party in order to comply with law or where we believe such action is necessary in order to comply with law or detect, protect or defend us and/or other third parties against error, negligence, breach of contract, theft, fraud and other illegal or harmful activity, to comply with our audit and security requirements, and to audit compliance with our corporate policies, procedures, legal and contractual obligations;</p>
        <p>(h) HM Revenue & Customs, regulators and other authorities who require reporting of processing activities in certain circumstances.</p>
        <p>(i) to anyone to whom we transfer or may transfer our rights and duties under our agreement with you.</p>
        <h2>PUBLIC (OR INTERACTIVE) AREAS OF OUR WEBSITES</h2>
        <p>Information that you post on or through the public areas of the site (e.g., chat rooms, bulletin boards and discussion groups) are generally accessible to, and may be collected and used by, others and may result in unsolicited messages or other contact from others. You should not provide personal information about yourself in public (or interactive) areas of the site. Such personal information is not covered under this Privacy Statement.</p>
        <h2>SECURITY</h2>
        <p>We take security seriously and we take precautions to keep your personal information secure. We have put in place appropriate physical, electronic and managerial procedures to safeguard the information we collect. We have no control over the privacy of any communications while in transit to us. We recommend that you not include confidential, proprietary or sensitive information in such communications.</p>
        <h2>HOW LONG WILL WE KEEP YOUR PERSONAL DATA?</h2>
        <p>We access, retain, store and use personal data for the least amount of time necessary pursuant to our relationship with you (e.g., to provide you with or access to our products and services), in accordance with our data retention policies and applicable law. We do not process more personal data than is necessary to fulfill our obligations to you or at law or for purposes stated in this Privacy & Cookie Policy. </p>
        <p>In the unlikely event that we believe that the security of your personal information in our possession or control may have been compromised, we may seek to notify you of that development. If a notification is appropriate, we would endeavor to do so as promptly as possible under the circumstances, and, to the extent we have your e-mail address, we may notify you by e-mail.</p>
        <h2>UNSUBSCRIBE, ACCESS, QUESTIONS AND FURTHER INFORMATION</h2>
        <p>At your request and where the law requires us to do so, we will confirm what personal information we hold about you, update your information, remove your information, fulfill specific opt-out requests, including requests where you have previously opted-in with respect to the use of your personal information, and/or correct any inaccuracies in such personal information if you contact us using the unsubscribe details provided below.</p>
        <p>If you would like to unsubscribe from The Bank Restaurant, please contact us at  <a href="mailto:info@thebankrestauranthuntly.com">info@thebankrestauranthuntly.com</a></p>
        <h2>LINKS</h2>
        <p>Our website contains links to other websites. This Privacy Policy only applies to this website, so when you access other websites via our links you should read their own privacy policies. Please be aware that we have no control over these websites and our Privacy Statement does not apply to these sites. We encourage you to read the privacy statements and terms and conditions of linked or referenced websites you enter.</p>
        <p>As required, this Privacy Statement will be supplemented by additional legal requirements in jurisdictions where we conduct business. Nothing in this Privacy Statement or otherwise will create, or add to, any right or claim (whether legal, equitable or otherwise) that any individual or person may have at law or otherwise against the company or any third party or any of their respective directors, officers, employees, agents or representatives; nor will the existence of this Privacy Statement or its application impose or add to any obligations or liability upon The Bank that does not already otherwise have under law.</p>
        <h2>AGGREGATED DATA</h2>
        <p>We also collect, use, and share Aggregated Data such as statistical or demographic data for any purpose. Aggregated Data may be derived from your personal data but is not considered personal data in law as this data does not directly or indirectly reveal your identity. For example, we may aggregate your Usage Data to calculate the percentage of users accessing a specific website feature. However, if we combine or connect Aggregated Data with your personal data so that it can directly or indirectly identify you, we treat the combined data as personal data which will be used in accordance with this privacy policy.</p>
        <p>PRIVATE POLICY ADDITIONS </p>
        <p>We review this from time to time.  We are legally required to hold some types of information to fulfil our legal obligations (e.g. financial record keeping).  We will hold your personal information on our systems only for as long as is necessary for the relevant activity or to facilitate any future stays, or as long as it is set out in any relevant contract you hold with us.  </p>
        <h2>YOUR RIGHTS</h2>
        <p>Under data protection laws, you have the following rights, which you can exercise free of charge.</p>
        <ul className="policy_ul">
          <li>The accuracy of your information is important to us. You have the right to require us to correct any mistakes in your personal information we hold. We are working on ways to make it easier for you to review and correct this information. In the meantime, if any of the information we hold about you is inaccurate or out of date, please let us know.</li>
          <li>You have the right to ask for a copy of the information The Bank holds about you.</li>
          <li>You have the right to require us to delete your personal information, in certain situations.</li>
          <li>You have the right to receive a copy of all personal information we hold about you in a structured, commonly used data and machine readable format and/or transmit that data to a third party. We will provide this upon request.</li>
          <li>You have the right to object at any time to our processing of your personal information for direct marketing (including profiling) and in certain other situations (e.g. processing carried out for the purpose of our legitimate interests).  You can change your marketing preferences at any time. If you do not want to receive direct marketing communications from us, please follow the unsubscribe link on our communications or contact us at <a href="mailto:info@thebankrestauranthuntly.com">info@thebankrestauranthuntly.com</a></li>
          <li>You have the right to not be subject to decisions made automatically based on your personal information (including profiling). The Bank does not make any automated decisions based on information we hold about you.</li>
          <li>You have the right to request we restrict the processing of your personal information for certain purposes only (e.g. if you contest the accuracy of the data).</li>
        </ul>
        <p>If you think we have not handled your personal information correctly, you have the right to lodge a complaint with the Information Commissioner’s Office who act as the Supervisory Authority for enforcement of relevant data protection legislation in the UK. More information about how to make a complaint can be found at: https://ico.org.uk/concerns/</p>
        <p>You have the right to expect us to carry out any request with respect to any of your rights under data protection laws within 30 days where the request is not manifestly unfounded or excessive. If you wish to exercise any of the rights set out above, please contact us. You will not have to pay a fee to access your personal data (or to exercise any of the other rights). However, we may charge a reasonable fee if your request is clearly unfounded, repetitive, or excessive. Alternatively, we may refuse to comply with your request in these circumstances. We may need to request specific information from you to help us confirm your identity and ensure your right to access your personal data (or to exercise any of your other rights). This is a security measure to ensure that personal data is not disclosed to any person who has no right to receive it. We may also contact you to ask you for further information in relation to your request to speed up our response. </p>
        <p>We try to respond to all legitimate requests within one month. Occasionally it may take us longer than a month if your request is particularly complex or you have made several requests. In this case, we will notify you and keep you updated.</p>
        <p>Castlebank Hotels & Restaurants LTD incorporated and registered in Scotland with company number SC699156 and whose address is 36 Gordon Street, Huntly AB548EQ</p>
      </div>
    </Container>
  );
};

export default PrivacyPolicyPage;
