"use client";
import React from "react";
import { Container } from "react-bootstrap";

const TermsAndConditionPage = () => {
  return (
    <Container className="bg-white">
      <div className="privacy_policy_section">
        <h1>Terms and Conditions of Website Use</h1>
        <h2>INTRODUCTION</h2>
        <p>Please read this Terms of Service Agreement (these “Terms”) carefully, as it constitutes legally binding terms and conditions between you, as the user of our Sites and Apps, and Castlebank Hotels & Restaurants LTD, its group companies, subsidiaries, associates and its affiliates (“The Bank” “we” “us” or “our”).  These Terms apply to your use of and access to our Sites and Apps, and apply whether you are accessing our Sites and Apps via a wireless or mobile device, a tablet a personal computer or any other technology or device (each, a “Device”). If you are entering into these Terms in connection with your employment, you represent to us that you are authorized to bind your employer and all references to “you” and “your” shall refer to you and your employer.  If you do not agree to these Terms, then you have the choice not to utilize our Sites or Apps.  </p>
        <p>By using our site, you indicate that you accept these terms of use and that you agree to abide by them. If you do not agree to these terms of use, please refrain from using our site. </p>
        <p>We reserve the right to amend these Terms & Conditions from time to time without notice and at our Conditions, which shall come into effect once posted. Your continued use of the Site constitutes acceptance of these Terms & Conditions, including our Privacy Statement. We reserve the right to change, modify, suspend or discontinue any portion of the Site at any time. We may also impose limits on certain features or restrict your access to parts or the entire Site without notice or liability. The Site is operated by a member of the Castlebank Hotels & Restaurants LTD incorporated and registered in Scotland with company number SC699156 and whose address is 36 Gordon Street, Huntly AB548EQ </p>
        <h2>ELIGIBILITY</h2>
        <p>COMPLIANCE-Use of our Sites and Apps is limited to be used and accessed by people who are of legal age to purchase and consume alcohol. If you are of legal age in your country/State of residence and the country/State from which you are accessing this Website, please continue. If you are not, please exit this Website immediately.  By using our Sites and Apps, you represent and warrant to us that you are of legal age.  You also represent and warrant that your use of our Sites and Apps does not violate any law, rule or regulation to which you may be subject, including any terms, conditions or requirements promulgated by any provider of a Third Party Platform. Certain features of our Sites and Apps may be subject to heightened age and/or other eligibility requirements and restrictions. </p>
        <h2>RIGHTS </h2>
        <p>All rights in all material and content (including, but not limited to, text, images, web pages, sound, software (including, code, interface and website structure) and video, and the look and feel, design and compilation thereof) at the Site are owned by us or our licensors. You agree that you are permitted to use this material and/or content only as set out in these Terms & Conditions or as otherwise expressly authorised in writing by us or our licensors, and that you may not otherwise copy, reproduce, transmit, publicly perform, distribute, commercially exploit, adapt, translate, modify, bundle, merge, share or make available to any person, or create derivative works of such material or content. Our status (and that of any identified contributors) as the authors of the material on our site must always be acknowledged.</p>
        <h2>INTELLECTUAL PROPERTY RIGHTS </h2>
        <p>We are the owner and/or authorised user of all trademarks, service marks, design marks, patents, copyrights, database rights and all other intellectual property appearing on or contained within the Site, (e.g., audio-visual content, photographs, audio, images, illustrations, graphics, video, copy, software, etc.), code, data and materials displayed on or otherwise made available through the Sites and Apps, including as contained in any advertisements and the “look and feel” of such content (collectively, “Content”) unless otherwise indicated . This includes all intellectual property and proprietary rights in such content. Except as provided in these Terms & Conditions, use of the Site does not grant you any right, title, interest or license to any such intellectual property you may access on the Site. Except as provided in these Terms & Conditions, any use or reproduction of the intellectual property is prohibited.</p>
        <h2>COPYING </h2>
        <p>You may view the Site and you are welcome to print hard copies of material on it solely for your lawful, personal, non-commercial use.  The framing or scraping of or in-line linking to our Sites and Apps or any Content, and/or the use of webcrawler, spidering or other automated means to access, copy, index, process and/or store any Content, other than as expressly authorized by us, is prohibited.  You further agree to abide by exclusionary protocols (e.g., Robot.txt, Automated Content Access Protocol (ACAP), etc.) used in connection with our Sites and Apps. Additionally, you are not permitted to alter, delete or conceal in any manner any copyright, Trademark, or other notices contained on our Sites and Apps, including, without limitation, notices on any Content you transmit, display, print, stream or reproduce from our Sites and Apps. All other rights are reserved. </p>
        <h2>LINKING </h2>
        <p>We welcome and encourage other websites to link to the information that is hosted on these pages, and you don’t have to ask permission to link to https://www.thebankrestauranthuntly.com However, links to Linked Sites do not constitute an endorsement by or association with us of such sites or the content, products, advertising or other materials presented on such sites. We have no control over these Linked Sites and do not edit or monitor them. You acknowledge and agree that we are not responsible or liable, directly or indirectly, for any damage, loss or cost caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on such Linked Sites. Where our site contains links to other sites and resources provided by third parties, these links are provided for your information only. We have no control over the contents of those sites or resources and accept no responsibility for them or for any loss or damage that may arise from your use of them. You acknowledge and agree that we have no responsibility for the information provided by websites to which you may link from the Site (“Linked Sites”). </p>
        <h2>TERMS OF USE AND ACCEPTABLE USAGE POLICY RELATING TO PUBLIC FORUMS</h2>
        <p>The Site may contain interactive services, including, but not limited to, discussion groups, news groups, bulletin boards, chat rooms and blogs (collectively, “Public Forums”), which may allow you to post, transmit or submit information, including, but not limited to, writings, images, illustrations, audio recording and video recordings. We may or may not actively monitor use of, or content or materials posted on, our Public Forums. Similarly, we may or may not exercise editorial control over the content of any Public Forum. As a result, you may be exposed to content on our Public Forums that is inaccurate, fraudulent or deceptive or that you find offensive or objectionable. Your use of Public Forums is at your own risk.</p>
        <p>We reserve the right, but are not obliged, to monitor our Public Forums and to remove or alter any content, which we consider, in our sole discretion, constitutes a misuse of these rules. We may restrict, suspend or terminate your use of these services or the Site where we believe that there has been such a misuse.</p>
        <p>Any content, information or material posted to a Public Forum (“Postings”) will be deemed not to be confidential or secret. You understand that personal and other information (e.g., username, email address, phone number) that you post on or through Public Forums is generally accessible to, and may be collected and used by, others and may result in unsolicited messages or other contact from others. You should not include any personally identifiable information about yourself or any other person in any Postings. We reserve the right, but not the obligation, to remove any Postings that contain personally identifiable information. We shall not be liable for the use or misuse of any information or data, including personal information, that you post on our Public Forums.</p>
        <p>You represent and warrant that your Postings are original to you, do not infringe on another party’s intellectual property rights, are not obscene, vulgar, offensive, malicious, discriminatory, defamatory or otherwise unlawful, that no other party has any rights thereto, and that any “moral rights” in your Postings have been waived, and you grant us a royalty-free, unrestricted, worldwide, perpetual, irrevocable, non-exclusive and fully transferable, assignable and sub-licensable right and license to use, copy, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such Postings (in whole or part) and / or to incorporate them in other works in any form, media, or technology now known or later developed for editorial, commercial, non-commercial, promotional or any other purpose.</p>
        <p>Content, information and materials posted by users to public forums are not endorsed by us. It is your responsibility to evaluate and confirm the accuracy of information provided by other users on or through public forums. The opinions expressed in Public Forums are not necessarily ours. Any statements, advice and opinions made by participants are those of such participants only. We shall not be held responsible for any statements, advice, opinions or other content or materials on Public Forums. You release us from claims and demands of every kind and nature, known and unknown, howsoever arising out of or in any way connected with a dispute with another user of the Site.</p>
        <h2>MATERIALS SUBMITTED BY YOU </h2>
        <p>Unless specifically requested, we do not solicit nor do we wish to receive any confidential, secret or proprietary information or other material from you through the Site, any of its services, by email, or in any other way. Any information or material submitted by you, and which has not been specifically requested by us, will be deemed not to be confidential, secret or proprietary. You agree that any information or materials submitted by you to the Site, whether ideas, creative concepts or other materials, in any format, including, but not limited to, writings, images, illustrations, audio recordings, and video recordings, may be used, reproduced and disclosed by us without restriction for whatever purpose we deem fit and without payment of any sum or acknowledgement of you as their source. You also warrant that any “moral rights” in posted materials have been irrevocably waived by the appropriate authors. We shall have no liability for any loss or damage suffered by you as a result of use or disclosure of such materials by us to the extent permitted by law. This paragraph does not affect any rights you may have under data privacy laws that protect your personal information or similar privacy laws, to the extent that such rights cannot be excluded.</p>
        <h2>YOUR RESPONSIBILITY </h2>
        <p>You should always verify the information set out in the Site with independent authorities before acting or relying on it. It is your responsibility to use virus-checking software on any material downloaded from the Site and to ensure the compatibility of such software with your equipment.  In circumstances where you provide us with information relating to any third parties, you warrant that you have received that third party’s consent in relation to such disclosure and that the third party has been informed of, and agrees to, our Privacy Statement and the uses that we may make of such information.</p>
        <h2>USER INFORMATION </h2>
        <p>In the course of your use of the Site, you may be asked to provide personal information to us (such information referred to hereinafter as “User Information”). Our information collection and use policies with respect to such User Information are set forth in the Site Privacy Statement, which Privacy Statement is incorporated into these Terms & Conditions by reference. You acknowledge and agree that you are solely responsible for the accuracy and content of the User Information.</p>
        <h2>DATA AND WIRELESS ACCESS CHARGES</h2>
        <p>Certain of our Apps or Sites may require data access, and the provider of data access (e.g., network operator, wireless carrier, etc.) for your Device may charge you data access fees in connection with your use of such including, without limitation, wireless carrier messaging and other communication, messaging and data fees and charges.  The Bank will not be responsible for any such data access fees and charges in connection with your use of any Sites or Apps. Further, the use or availability of certain Sites or Apps may be prohibited or restricted by your wireless carrier and/or data access provider, and not all Sites and Apps may work with all wireless carriers, networks, platforms, services or devices.</p>
        <h2>THIRD PARTY GOODS AND SERVICES </h2>
        <p>We do not vouch for those persons, companies and other organisations whose goods or services may be accessed or displayed through or on the site.</p>
        <h2>NO WARRANTIES </h2>
        <p>The site is provided “as is,” and your use thereof is at your own risk. we, our officers, directors, employees, agents and assigns, disclaim, to the fullest extent permitted by law, all express and implied warranties, including, without limitation, any warranties of merchantability, fitness for a particular purpose, performance, title and non-infringement. We do not warrant that the site will be free from viruses, available, accessible, error-free, uninterrupted or that the contents will be accurate. Although we take reasonable steps to secure the site, you acknowledge that the internet is not a completely secure medium and we make no warranties, express or implied, that any information or materials you post on or transmit through the site will be safe from unauthorised access or use. If you are dissatisfied with the site, your sole remedy is to discontinue using the site.</p>
        <h2>LIABILITY </h2>
        <p>To the fullest extent permitted by law we, our officers, directors, employees, agents and assigns, hereby disclaim all liability for any loss, cost or damage (direct, indirect, consequential, or otherwise) suffered by you as a result of your use of the site or from any computer virus transmitted through the site, or other sites accessed from the site, whether such loss, cost or damage arises from our negligence or otherwise and even if we are expressly informed of the possibility of such loss or damage. In no event shall our total liability to you for all damages, costs, losses and causes of action in the aggregate (whether in contract, tort, including, but not limited to, negligence, strict liability or product liability) and whether or not we were or should have been aware or advised or the possibility of such damage arising from these terms and conditions, including our privacy statement, or use of the site exceed, in the aggregate, 75 GBP</p>
        <p>TO THE EXTENT ALLOWED BY LAW, EACH OF YOU AND THE BANK AND/OR ITS AFFILIATED COMPANIES WAIVE ANY RIGHT TO PURSUE DISPUTES ON A CLASS WIDE BASIS; THAT IS, TO EITHER JOIN A CLAIM WITH THE CLAIM OF ANY OTHER PERSON OR ENTITY OR ASSERT A CLAIM IN A REPRESENTATIVE CAPACITY ON BEHALF OF ANYONE ELSE IN ANY ARBITRATION.</p>
        <h2>INDEMNITY </h2>
        <p>You will indemnify us and our officers, directors, agents, employees and representatives, against any loss, damage or cost incurred by us arising out of your use of the Site, any of its services or any information accessible over or through the Site, including information obtained from Linked Sites, your submission or transmission of information or material on or through the Site or your violation of these Terms & Conditions or any other laws, regulations and rules. You will also indemnify against any claims that information or material that you have submitted to us is in violation of any law or in breach of any third-party rights (including, but not limited to, claims in respect of defamation, invasion of privacy, breach of confidence, infringement of copyright or infringement of any other intellectual property right). We reserve the right to exclusively defend and control any claims arising from the above and any such indemnification matters and that you will fully cooperate with us in any such defenses.</p>
        <h2>RESTRICTION, SUSPENSION AND TERMINATION </h2>
        <p>We may restrict, suspend or terminate your access to the Site and/or your ability to avail of the services on the Site, including interactive services, if we believe that you have breached these Terms & Conditions at any time. Any such restriction, suspension or termination will be without prejudice to any rights that we may have against you in respect of your breach of these Terms & Conditions. We may also remove the Site as a whole or any sections or features of the Site at any time. Please note that we have the ability to trace your IP address and if necessary, contact your ISP in the event of a suspected breach of these Terms & Conditions.</p>
        <h2>ENTIRE AGREEMENT </h2>
        <p>These Terms & Conditions, including our Privacy Statement, constitute the entire agreement between you and us in relation to its subject matter and supersedes any and all prior promises, representations, agreements, statements and understandings whatsoever between us. To the extent that software is available through the Site, such software may be subject to a license agreement that is distributed or included with such software and you agree to abide by the terms and conditions of any such license agreements. The failure by us to exercise or enforce any right or provision of the Terms & Conditions shall not constitute a waiver of such right or provision. If any provision of the Terms & Conditions is found by a court of competent jurisdiction to be unenforceable or invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of the Terms & Conditions shall remain in full force and effect. We may assign or otherwise transfer our rights and obligations in terms of these standard terms and conditions to third parties.</p>
        <h2>COPYRIGHT AND IP AGENT FOR THE UNITED KINGDOM </h2>
        <p>We respect the intellectual property rights of others and require that the people who use the Site do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, please forward the following information to the Copyright Agent named below:</p>
        <p>Your address, telephone number, and email address;</p>
        <p>A description of the copyrighted work that you claim has been infringed;</p>
        <p>A description of the alleged infringing activity and where the alleged infringing material is located;</p>
        <p>A statement by you that you have a good faith belief that the disputed use is not authorised by you, the copyright owner, its agent, or the law;</p>
        <p>An electronic or physical signature of the person authorised to act on behalf of the owner of the copyright interest; and
          A statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorised to act on the copyright owner’s behalf.

        </p>
        <p>  Copyright Agent: Castlebank Hotels & Restaurants LTD:  <a href="mailto:info@thebankrestauranthuntly.com">info@thebankrestauranthuntly.com</a></p>
        <h2>EXPORT CONTROLS </h2>
        <p>To the extent that software or technical data is accessible through the Site, such software or technical data may be subject to export, re-export and/or import controls imposed by the United Kingdom or any other jurisdiction and may not be downloaded or otherwise exported or re-exported in violation of the laws of any applicable jurisdiction including, but not limited to: (a) into (or to a national or resident of) any country to which the U.K. has placed an embargo or which is subject to relevant export restrictions; (b) to anyone on the U.K. Treasury Department’s Specially Designated Nationals list, or (c) in violation of the U.K. Commerce Department’s Table of Denial Orders.</p>
        <h2>LAW AND JURISDICTION </h2>
        <p>These Terms & Conditions, including the Privacy Statement and any matter relating to the Site, shall be governed by Scottish Law without regard to its conflict of law rules. Any legal proceeding arising out or relating to these Terms and Conditions against or relating to us or any indemnified party under these Terms and Conditions will be subject to the exclusive jurisdiction of court sitting in Scotland and you irrevocably consent to the jurisdiction of such courts.</p>
        <p>Castlebank Hotels & Restaurants LTD All rights reserved. </p>
      </div>
    </Container>
  );
};

export default TermsAndConditionPage;
